version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_global
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_global
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
    networks:
      - pg_network
      - traefik_proxy

volumes:
  postgres-data:
  pgadmin-data:

networks:
  pg_network:
    driver: bridge
  traefik_proxy:
    external: true
